config/routes.rb
require 'subdomain'

Rails.application.routes.draw do

    root 'mains#index'
    resources :websites 
    

    constraints(Subdomain) do
        devise_for :users, :controllers => { registrations: 'registrations', passwords: 'passwords' }
        resources :users, except: [:show]

        mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
        resources :teams
        resources :commissions
        resources :salevalues
        resources :sales
        resources :units
            
        get '/users/:user_id/sales' => "users#sales"
        post '/users/:user_id/sales' => "users#sales"
        get '/requests' => "users#requests"
        post '/request' => "users#approve"
        get '/approve' => "users#approve"
        post '/change_user' => 'users#change_user'
        get '/revert_user' => 'users#revert_user'

        get '/dashboard' => "pages#dashboard"
        get '/pages/sales' => "pages#sales"
        get '/pages/units' => "pages#units"
        get '/pages/users' => "pages#users"


        # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
        resources :sales, controller: "sales"
        post '/change_status' => "sales#change_status"
        post '/sales/email' => "sales#email"

        resources :teams, controller: "teams"
        get '/teams/:team_id/sales' => "teams#sales"
        post '/teams/:team_id/sales' => "teams#sales"
        get '/teams_sales_summary' => "teams#members" 
        post '/teams_sales_summary' => "teams#members" 
        get '/teams/:team_id/profiles' => "teams#profiles"

            
        get '/charts/uptodate/barchart' => "charts#uptodate_barchart"
        post '/charts/monthly_barchart' => "charts#monthly_barchart"
        get '/charts/monthly_barchart' => "charts#monthly_barchart"
        post '/charts/barchart' => "charts#barchart"
        get '/charts/barchart' => "charts#barchart"

        resources :projects

        post '/search_by_name' => 'searches#search_by_name'
        post '/search_team_sales' => 'searches#search_team_sales'
        get '/search_team_sales' => 'searches#search_team_sales'
        post '/search_individual_sales' => 'searches#search_individual_sales'
        get '/search_individual_sales' => 'searches#search_individual_sales'

        get '*path' => redirect('/')
    end

    get '*path' => redirect('/')
    
end

# Session routes for Authenticatable (default)
 #     new_user_session GET    /users/sign_in                    {controller:"devise/sessions", action:"new"}
 #         user_session POST   /users/sign_in                    {controller:"devise/sessions", action:"create"}
 # destroy_user_session DELETE /users/sign_out                   {controller:"devise/sessions", action:"destroy"}

# Password routes for Recoverable, if User model has :recoverable configured
   #  new_user_password GET    /users/password/new(.:format)     {controller:"devise/passwords", action:"new"}
   # edit_user_password GET    /users/password/edit(.:format)    {controller:"devise/passwords", action:"edit"}
   #      user_password PUT    /users/password(.:format)         {controller:"devise/passwords", action:"update"}
   #                    POST   /users/password(.:format)         {controller:"devise/passwords", action:"create"}

# Confirmation routes for Confirmable, if User model has :confirmable configured
# new_user_confirmation GET    /users/confirmation/new(.:format) {controller:"devise/confirmations", action:"new"}
#     user_confirmation GET    /users/confirmation(.:format)     {controller:"devise/confirmations", action:"show"}
#                       POST   /users/confirmation(.:format)     {controller:"devise/confirmations", action:"create"}

app/models/salevalue.rb
class Salevalue < ApplicationRecord
	include PgSearch
	pg_search_scope :search_sales, 
	:associated_against => {
		:sale => [:id,:status,:date,:buyer]
	}

	belongs_to :user, optional: true
	belongs_to :sale, optional: true

	accepts_nested_attributes_for :user, :allow_destroy => true, reject_if: proc { |attributes| attributes['prefered_name'].blank?}

	def self.active_sv
		self.joins(:sale).where("sales.status"=>["Booked","Done"])
	end

	def self.TotalNetValue
		self.active_sv.sum(:nett_value)
	end

	def self.TotalComm
		self.active_sv.sum(:comm)
	end

	def self.TotalSPA
		self.active_sv.sum(:spa)
	end

	def self.TotalSales
		self.active_sv.count
	end

	def recalculate(unit)
		self.update(spa:unit.spa_price*self.percentage/100, nett_value:unit.nett_price*self.percentage/100, comm:unit.comm*self.percentage/100)
	end

end

app/helpers/salevalues_helper.rb
module SalevaluesHelper
end

app/views/salevalues/_form.html.erb
<%= form_for(salevalue) do |f| %>
  <% if salevalue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(salevalue.errors.count, "error") %> prohibited this salevalue from being saved:</h2>

      <ul>
      <% salevalue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/salevalues/edit.html.erb
<h1>Editing Salevalue</h1>

<%= render 'form', salevalue: @salevalue %>

<%= link_to 'Show', @salevalue %> |
<%= link_to 'Back', salevalues_path %>

app/views/salevalues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Salevalues</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @salevalues.each do |salevalue| %>
      <tr>
        <td><%= link_to 'Show', salevalue %></td>
        <td><%= link_to 'Edit', edit_salevalue_path(salevalue) %></td>
        <td><%= link_to 'Destroy', salevalue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Salevalue', new_salevalue_path %>

app/views/salevalues/new.html.erb
<h1>New Salevalue</h1>

<%= render 'form', salevalue: @salevalue %>

<%= link_to 'Back', salevalues_path %>

app/views/salevalues/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_salevalue_path(@salevalue) %> |
<%= link_to 'Back', salevalues_path %>