config/routes.rb
require 'subdomain'

Rails.application.routes.draw do

    root 'mains#index'
    resources :websites 
    

    constraints(Subdomain) do
        devise_for :users, :controllers => { registrations: 'registrations', passwords: 'passwords' }
        resources :users, except: [:show]

        mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
        resources :teams
        resources :commissions
        resources :salevalues
        resources :sales
        resources :units
            
        get '/users/:user_id/sales' => "users#sales"
        post '/users/:user_id/sales' => "users#sales"
        get '/requests' => "users#requests"
        post '/request' => "users#approve"
        get '/approve' => "users#approve"
        post '/change_user' => 'users#change_user'
        get '/revert_user' => 'users#revert_user'

        get '/dashboard' => "pages#dashboard"
        get '/pages/sales' => "pages#sales"
        get '/pages/units' => "pages#units"
        get '/pages/users' => "pages#users"


        # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
        resources :sales, controller: "sales"
        post '/change_status' => "sales#change_status"
        post '/sales/email' => "sales#email"

        resources :teams, controller: "teams"
        get '/teams/:team_id/sales' => "teams#sales"
        post '/teams/:team_id/sales' => "teams#sales"
        get '/teams_sales_summary' => "teams#members" 
        post '/teams_sales_summary' => "teams#members" 
        get '/teams/:team_id/profiles' => "teams#profiles"

            
        get '/charts/uptodate/barchart' => "charts#uptodate_barchart"
        post '/charts/monthly_barchart' => "charts#monthly_barchart"
        get '/charts/monthly_barchart' => "charts#monthly_barchart"
        post '/charts/barchart' => "charts#barchart"
        get '/charts/barchart' => "charts#barchart"

        resources :projects

        post '/search_by_name' => 'searches#search_by_name'
        post '/search_team_sales' => 'searches#search_team_sales'
        get '/search_team_sales' => 'searches#search_team_sales'
        post '/search_individual_sales' => 'searches#search_individual_sales'
        get '/search_individual_sales' => 'searches#search_individual_sales'

        get '*path' => redirect('/')
    end

    get '*path' => redirect('/')
    
end

# Session routes for Authenticatable (default)
 #     new_user_session GET    /users/sign_in                    {controller:"devise/sessions", action:"new"}
 #         user_session POST   /users/sign_in                    {controller:"devise/sessions", action:"create"}
 # destroy_user_session DELETE /users/sign_out                   {controller:"devise/sessions", action:"destroy"}

# Password routes for Recoverable, if User model has :recoverable configured
   #  new_user_password GET    /users/password/new(.:format)     {controller:"devise/passwords", action:"new"}
   # edit_user_password GET    /users/password/edit(.:format)    {controller:"devise/passwords", action:"edit"}
   #      user_password PUT    /users/password(.:format)         {controller:"devise/passwords", action:"update"}
   #                    POST   /users/password(.:format)         {controller:"devise/passwords", action:"create"}

# Confirmation routes for Confirmable, if User model has :confirmable configured
# new_user_confirmation GET    /users/confirmation/new(.:format) {controller:"devise/confirmations", action:"new"}
#     user_confirmation GET    /users/confirmation(.:format)     {controller:"devise/confirmations", action:"show"}
#                       POST   /users/confirmation(.:format)     {controller:"devise/confirmations", action:"create"}

app/models/project.rb
class Project < ApplicationRecord
	has_many :sales
	has_many :units
	has_many :commissions, dependent: :destroy

	validates :name, uniqueness:{ message: "already existed"}

	before_validation :titleize

	accepts_nested_attributes_for :commissions, :allow_destroy => true

	def commission(date)
		self.commissions.where('effective_date <= ?', date).order("effective_date DESC").first
	end

	private
	
	def titleize
		self.name = self.name.titleize
	end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	
	before_action :login_required
	before_action :first_login
	before_action :leader_only
	before_action :save_path, only: [:new,:index,:edit]


	def new
		@project = Project.new
		@title = "New Project"
	end

	def create
		@project = Project.new(project_params)
		if @project.save
			flash[:success] = "Project created"
			redirect_to projects_path
		else
			flash.now[:danger] = @project.errors.full_messages.first
			render "new"
		end
	end

	def index
		@projects = Project.all.includes(:commissions).page params[:page]
		@title = "Projects"
	end

	def edit
		@project = Project.find(params[:id])
		@title = "Edit project"
	end

	def update
		@project = Project.find(params[:id])
		if @project.update(project_params)
			comms = @project.commissions.select {|comm| comm.updated_at.to_date == Date.today }
			if comms != []
				@project.sales.each do |sale|
					sale.set_commission_id
					sale.save(validate: false)
					sale.calculate
				end
			end
			flash[:success] = "Project updated"
			redirect_to projects_path
		else
			flash.now[:danger] = @project.errors.full_messages.first
			render "edit"
		end
	end

	def destroy
		project = Project.find(params[:id])
		project.destroy
		flash[:info] = "Project deleted"
		redirect_to projects_path
	end

	private

	def project_params
		params.require(:project).permit(:name,commissions_attributes: [:id,:percentage,:effective_date,:_destroy])
	end
end
# Project.first.sales.each do |x|
# 	ActiveRecord::Base.connection.execute("UPDATE sales SET commission_id = (SELECT commissions.id FROM sales JOIN projects ON sales.project_id = projects.id JOIN commissions ON commissions.project_id = projects.id WHERE commissions.effective_date <= #{x.date} ORDER BY commissions.effective_date DESC LIMIT 1) WHERE id = #{x.id};")
# Project.first.sales.each do |x|
# 	ActiveRecord::Base.connection.execute("UPDATE units SET comm = ( SELECT commissions.percentage/100*units.nett_price*0.94 FROM commissions JOIN sales ON commission_id = commissions.id JOIN units ON sales.id = sale_id WHERE sales.id = #{x.id}) WHERE id = #{x.unit_id};")
# end
# Project.first.sales.each do |x|
# 	ActiveRecord::Base.connection.execute("UPDATE units SET comm_percentage = ( SELECT commissions.percentage FROM commissions JOIN sales ON commission_id = commissions.id JOIN units ON sales.id = sale_id WHERE sales.id = #{x.id}) WHERE id = #{x.unit_id};")
# end
		# comm = self.commission
		# unit = self.unit
		# unit.update(sale_id: self.id,project_id: self.project_id,comm: comm.percentage/100*unit.nett_price*0.94,comm_percentage: comm.percentage)
		# self.salevalues.each do |sv|
		# 	sv.recalculate(unit)
		# 	sv.user.recalculate
		# end	

# end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_commission.html.erb
  <div class="col-xs-5 col-sm-5 col-md-5">
    <%= f.date_field :effective_date, placeholder: 'yyyy-mm-dd',class: "form-control datepicker",required: true %>
  </div>

  <div class="col-xs-5 col-sm-5 col-md-5">
   <%= f.number_field :percentage, class: "form-control",min: "0",max: "100",step: "any",required: true%>
  </div>

  <div class="col-xs-1 col-sm-1 col-md-1">
  	<%if f.object.sales == []%>
  		<%= f.link_to_remove "-",class: "ren_remove btn btn-default" %>
  	<%end%>
  </div>

app/views/projects/_form.html.erb
<div class="form-group">
  <%= form.label :name %>
  <%= form.text_field :name,class: "form-control" ,required: true%>
</div>

<div class="form-group">
	<label>Commissions:</label>
</div>

<div class="row">
	<div class="col-xs-5 col-sm-5 col-md-5">
	  <%= form.label :effective_date%>
	</div>

	<div class="col-xs-5 col-sm-5 col-md-5">
	 <%= form.label 'Percentage(%)' %>
	</div>
</div>

<div class="row form-group">
<%= form.fields_for :commissions,Commission.new do |f| %>

	<%=render "commission", f: f %>

<% end %>

<%= form.link_to_add "+", :commissions,class: "btn btn-default",style: "margin-left: 1px;" %>
</div>

<%= form.submit :submit,class: "btn btn-default" %>

app/views/projects/create.js.erb
$("wrapper").prepend("<div class=\"alert alert-danger\">"+
	"<a href=\"#\" class=\"close\" data-dismiss=\"alert\" aria-label=\"close\">&times;</a>"+
	"<%=j @message%></div>")

app/views/projects/edit.html.erb
<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4 well">
<h1 class="page-header">Edit Project</h1>
	<%if @project.sales == []%>
		<%=link_to "Delete","/projects/#{@project.id}",method: :delete, data: {confirm: "Are you sure?"}%>
	<%end%>
	<p></p>
	<%=nested_form_for @project do |form|%>
		<div class="form-group">
		  <%= form.label :name %>
		  <%= form.text_field :name,class: "form-control" ,required: true%>
		</div>

		<div class="form-group">
		<label>Commissions:</label>
		</div>

		<div class="row">
			<div class="col-xs-5 col-sm-5 col-md-5">
			  <%= form.label :effective_date%>
			</div>

			<div class="col-xs-5 col-sm-5 col-md-5">
			 <%= form.label 'Percentage(%)' %>
			</div>
		</div>

		<div class="row form-group">
		<%= form.fields_for :commissions do |f| %>

			<%=render "commission", f: f %>

		<% end %>

		<%= form.link_to_add "+", :commissions,class: "btn btn-default",style: "margin-left: 1px;" %>
		</div>

		<%= form.submit :submit,class: "btn btn-default" %>
	<%end%>

</div>

app/views/projects/index.html.erb
<div class="col-lg-12">
<h1 class="page-header">Projects</h1>

<table class="table-bordered" id="request-table">
<thead>
<tr>
<th rowspan="2">ID</th>
<th rowspan="2">Name</th>
<th colspan="2">Commission</th>
</tr>
<tr>
<th>Effective Date</th>
<th>Percentage (%)</th>
</tr>
</thead>
<tbody>
<%@projects.order("created_at").each do |project|%>
	<%project.commissions.each_with_index do |comm,index|%>
		<tr class='clickable-row' data-href="/projects/<%=project.id%>/edit">
		<%if index == 0%>
			<td rowspan="<%=project.commissions.length%>"><%=project.id%></td>
			<td rowspan="<%=project.commissions.length%>"><%=project.name%></td>
		<%end%>
		<td><%=comm.effective_date%></td>
		<td><%=comm.percentage%></td>
		</tr>
	<%end%>
<%end%>
</tbody>
</table>

<%= paginate @projects %>
</div>

app/views/projects/new.html.erb
<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4 well">
<h1 class="page-header">New Project</h1>

<%=nested_form_for @project do |form|%>

	<%=render partial: "form", object: form%>
<%end%>
</div>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>