config/routes.rb
require 'subdomain'

Rails.application.routes.draw do

    root 'mains#index'
    resources :websites 
    

    constraints(Subdomain) do
        devise_for :users, :controllers => { registrations: 'registrations', passwords: 'passwords' }
        resources :users, except: [:show]

        mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
        resources :teams
        resources :commissions
        resources :salevalues
        resources :sales
        resources :units
            
        get '/users/:user_id/sales' => "users#sales"
        post '/users/:user_id/sales' => "users#sales"
        get '/requests' => "users#requests"
        post '/request' => "users#approve"
        get '/approve' => "users#approve"
        post '/change_user' => 'users#change_user'
        get '/revert_user' => 'users#revert_user'

        get '/dashboard' => "pages#dashboard"
        get '/pages/sales' => "pages#sales"
        get '/pages/units' => "pages#units"
        get '/pages/users' => "pages#users"


        # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
        resources :sales, controller: "sales"
        post '/change_status' => "sales#change_status"
        post '/sales/email' => "sales#email"

        resources :teams, controller: "teams"
        get '/teams/:team_id/sales' => "teams#sales"
        post '/teams/:team_id/sales' => "teams#sales"
        get '/teams_sales_summary' => "teams#members" 
        post '/teams_sales_summary' => "teams#members" 
        get '/teams/:team_id/profiles' => "teams#profiles"

            
        get '/charts/uptodate/barchart' => "charts#uptodate_barchart"
        post '/charts/monthly_barchart' => "charts#monthly_barchart"
        get '/charts/monthly_barchart' => "charts#monthly_barchart"
        post '/charts/barchart' => "charts#barchart"
        get '/charts/barchart' => "charts#barchart"

        resources :projects

        post '/search_by_name' => 'searches#search_by_name'
        post '/search_team_sales' => 'searches#search_team_sales'
        get '/search_team_sales' => 'searches#search_team_sales'
        post '/search_individual_sales' => 'searches#search_individual_sales'
        get '/search_individual_sales' => 'searches#search_individual_sales'

        get '*path' => redirect('/')
    end

    get '*path' => redirect('/')
    
end

# Session routes for Authenticatable (default)
 #     new_user_session GET    /users/sign_in                    {controller:"devise/sessions", action:"new"}
 #         user_session POST   /users/sign_in                    {controller:"devise/sessions", action:"create"}
 # destroy_user_session DELETE /users/sign_out                   {controller:"devise/sessions", action:"destroy"}

# Password routes for Recoverable, if User model has :recoverable configured
   #  new_user_password GET    /users/password/new(.:format)     {controller:"devise/passwords", action:"new"}
   # edit_user_password GET    /users/password/edit(.:format)    {controller:"devise/passwords", action:"edit"}
   #      user_password PUT    /users/password(.:format)         {controller:"devise/passwords", action:"update"}
   #                    POST   /users/password(.:format)         {controller:"devise/passwords", action:"create"}

# Confirmation routes for Confirmable, if User model has :confirmable configured
# new_user_confirmation GET    /users/confirmation/new(.:format) {controller:"devise/confirmations", action:"new"}
#     user_confirmation GET    /users/confirmation(.:format)     {controller:"devise/confirmations", action:"show"}
#                       POST   /users/confirmation(.:format)     {controller:"devise/confirmations", action:"create"}

app/models/sale.rb
class Sale < ApplicationRecord
	include PgSearch
	pg_search_scope :search_sales, :against => [:id,:status,:date,:buyer], 
	:associated_against => {
		:users => :prefered_name,
		:unit => [:unit_no,:size],
		:project => :name
	}
	
	has_many :users, :through => :salevalues
	belongs_to :project, optional: true
	belongs_to :commission, optional: true
	belongs_to :unit, optional: true, :dependent => :destroy
	has_many :salevalues, :dependent => :destroy
	has_many :salevalues2, class_name: "Salevalue", :dependent => :destroy

	after_create :after_save_action, :unless => :skip_callback
	before_validation :set_commission_id, :unless => :skip_callback

	attr_accessor :skip_callback

	validates :commission_id, presence: {message: "is not available for that date. Check with your leader for more details."}

	accepts_nested_attributes_for :salevalues, :allow_destroy => true, reject_if: proc { |attributes| attributes['user_id'].blank? ||  attributes['percentage'].blank?}
	accepts_nested_attributes_for :salevalues2, :allow_destroy => true, reject_if: proc { |attributes| attributes['percentage'].blank?}
	accepts_nested_attributes_for :unit

	enum status: ["Booked","Done","Canceled"]

	def self.not_canceled
		self.where.not(status: "Canceled")
	end

	def self.TotalNetValue
		self.where(status: ["Done","Booked"]).joins(:unit).sum(:nett_price)
	end

	def self.TotalComm
		self.where(status: ["Done","Booked"]).joins(:unit).sum("units.comm")
	end

	def self.TotalSPA
		self.where(status: ["Done","Booked"]).joins(:unit).sum(:spa_price)
	end

	def self.TotalSales
		self.where(status: ["Done","Booked"]).count
	end

	def calculate		
		comm = self.commission
		unit = self.unit
		unit.update(sale_id: self.id,project_id: self.project_id,comm: comm.percentage/100*unit.nett_price*0.94,comm_percentage: comm.percentage)
		self.salevalues.each do |sv|
			sv.recalculate(unit)
			# sv.user.recalculate
		end	
	end

	def after_save_action
		self.update(buyer: self.buyer.titleize,unit_id: unit.id)
		User.merge
		self.calculate
	end

	def set_commission_id
		commission = self.project.commission(self.date)
		if commission.present?
			self.commission_id = commission.id 
		else
			self.commission_id = nil
		end
	end



end

app/controllers/sales_controller.rb
class SalesController < ApplicationController


	skip_before_action :verify_authenticity_token, only: :change_status
	before_action :login_required
	before_action :first_login
	before_action :sales_for_ancestors_only, only: [:edit, :update, :destroy]
	before_action :save_path,only: [:new,:edit]
	before_action :set_mailer_host, only: [:create]

	def new
		@sale = Sale.new
		@title = "New sale"
	end

	def create
		@sale = Sale.new(new_sale_params)
		if @sale.save
			UserMailer.generate_report(current_user.email, @sale, website_name).deliver
			flash[:success] = "Sale record created"	
			redirect_to "/"
		else
			flash.now[:danger] = @sale.errors.full_messages.first
			render 'new'
		end
	end

	def edit
		@sale = Sale.find(params[:id])
		@title = "Edit sale \##{params[:id]}"
	end

	def update
		@sale = Sale.find(params[:id])
		if @sale.update(new_sale_params)
			@sale.after_save_action
			flash[:success] = "Sale record updated"	
			redirect_to "/sales/#{@sale.id}/edit"
		else
			flash.now[:danger] = @sale.errors.full_messages.first
			render 'edit'
		end
	end

	def change_status
		@sales = Sale.where('id' => params[:tag_ids]).includes(salevalues: [:user])
		@sales.update_all(status: params[:status])
		redirect_to session[:path]
	end

	def destroy
		@sale = Sale.find(params[:id])
		@sale.destroy
		flash[:info] = "Sale \##{@sale.id} deleted"
		redirect_to '/'
	end

	def email
		@sale = Sale.find(params[:sale])
		if @sale.spa_sign_date == nil
			flash.now[:danger] = "SPA Sign Date must not be empty. Make sure you have updated the sale record."
			render "edit"
		else
			@sale.update(status: "Done")
			UserMailer.email_admin(@sale,current_user,website_name).deliver
			flash[:success] = "Email has been delivered"
			redirect_to "/sales/#{@sale.id}/edit"
		end
	end

	private
	def new_sale_params
		params.require(:sale).permit(:date,:project_id,:buyer,:package,:remark,:status,:unit_id,:spa_sign_date,:la_date,
			salevalues_attributes: [:id,:user_id,:percentage,:_destroy],
			salevalues2_attributes:[:id,:user_id,:percentage,:_destroy,
			user_attributes: [:id,:prefered_name,:password,:approved?,:_destroy]],
			unit_attributes: [:id,:sale_id,:unit_no,:size,:spa_price,:nett_price,:_destroy])
	end


end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_edit.html.erb
<div class="form-group">
  <%= form.label :date %>
  <%= form.date_field :date,class: "form-control datepicker", required: true,placeholder: "yyyy-mm-dd"%>
</div>

<div class="form-group">
<label><%= website_name%> REN</label>
</div>

<div class="row form-group">
<%= form.fields_for :salevalues do |sv_form| %>

<%=render "salevalue", sv_form: sv_form %>

<% end %>

<%= form.link_to_add "+", :salevalues,class: "btn btn-default",style: "margin-left: 1px;" %>
</div>

<div class="form-group">
<label>Other REN</label>
</div>

<div class="non-member row form-group" >
<%= form.fields_for :salevalues2,Salevalue.new do |sv2_form| %>

<%=render "salevalue2", sv2_form: sv2_form %>

<% end %>

<%= form.link_to_add "+", :salevalues2,class: "btn btn-default",style: "margin-left: 1px;" %>
</div>

<div class="form-group">
  <%= form.label :project%>
  <%= form.select :project_id, options_for_select(Project.all.order("name").pluck(:name,:id),:selected => @sale.project_id),{prompt: "Select Project"},{class: "form-control"}%>
</div>

<%= form.fields_for :unit,@sale.unit do |unit_form| %>

<%=render "unit", unit_form: unit_form%>

<% end %>

<div class="form-group">
  <%= form.label :buyer%>
  <%= form.text_field :buyer,class: "form-control", required: true %>
</div>

<div class="form-group">
  <%= form.label :status%>
  <%= form.select :status, options_for_select(Sale.statuses.keys.to_a,:selected => @sale.status),{prompt: "Select Status"},{class: "form-control"}%>
</div>

<div class="form-group">
  <%=form.label :spa_sign_date,"SPA Sign Date"%>
  <%=form.text_field :spa_sign_date,class: "datepicker form-control",placeholder: "yyyy-mm-dd"%>
</div>

<div class="form-group">
  <%=form.label :la_date,"LA Sign Date"%>
  <%=form.text_field :la_date,class: "datepicker form-control",placeholder: "yyyy-mm-dd"%>
</div>

<div class="form-group">
  <%= form.label :package %>
  <%= form.text_field :package,class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :remark %>
  <%= form.text_area :remark,class: "form-control", rows: "5" %>
</div>

app/views/sales/_emailModal.html.erb
<div id="emailModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Email this sale record to IQI admin?</h4>
      </div>

      <div class="modal-body">
        <%=form_tag sales_email_url(sale: @sale) do%>
            Date: <%=@sale.date%><br>
            <%@sale.salevalues.reverse.each_with_index do |sv,index|%>
            REN <%=index+1%>: <%=sv.user.prefered_name%> (<%=sv.percentage%>%)<br>
            <%end%>
            Project: <%=@sale.project.name%><br>
            Unit No: <%=@sale.unit.unit_no%><br>
            Size: <%=number_with_delimiter(@sale.unit.size)%> sqft<br>
            Buyer: <%=@sale.buyer%><br>
            SPA Price: RM <%=number_with_delimiter('%.2f' % @sale.unit.spa_price)%><br>
            Nett Price: RM <%=number_with_delimiter('%.2f' % @sale.unit.nett_price)%><br>
            SPA Sign Date: <%=@sale.spa_sign_date%><br>
            LA Sign Date: <%=@sale.la_date%><br>
            Package: <%=@sale.package%><br>
            Team: <%=website_name%><br><br>
          <%=submit_tag "Yes", class: "btn btn-default"%>
        <%end%>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/sales/_form.html.erb
<div class="form-group">
  <%= form.label :date %>
  <%= form.date_field :date,class: "form-control datepicker", required: true,placeholder: "yyyy-mm-dd"%>
</div>

<div class="form-group">
<label><%= website_name%> REN</label>
</div>
<div class="row">
  <div class="col-xs-5 col-sm-5 col-md-5">
    <%= form.label :ren, "Name"%>
  </div>

  <div class="col-xs-5 col-sm-5 col-md-5">
   <%= form.label 'Percentage(%)' %>
  </div>
</div>

<div class="row form-group">
<%= form.fields_for :salevalues,Salevalue.new do |sv_form| %>

<%=render "salevalue", sv_form: sv_form %>

<% end %>

<%= form.link_to_add "+", :salevalues,class: "btn btn-default",style: "margin-left: 1px;" %>
</div>


<div class="form-group">
<label>Other REN</label>
</div>

<div class="non-member row form-group" >
<%= form.fields_for :salevalues2,Salevalue.new do |sv2_form| %>

<%=render "salevalue2", sv2_form: sv2_form %>

<% end %>

<%= form.link_to_add "+", :salevalues2,class: "btn btn-default",style: "margin-left: 1px;" %>
</div>






<div class="form-group">
  <%= form.label :project%>
  <%= form.select :project_id, options_for_select(Project.all.order("name").pluck(:name,:id),:selected => @sale.project_id),{prompt: "Select Project"},{class: "form-control"}%>
</div>




<%= form.fields_for :unit,Unit.new do |unit_form| %>

<%=render "unit", unit_form: unit_form%>

<% end %>





<div class="form-group">
  <%= form.label :buyer%>
  <%= form.text_field :buyer,class: "form-control", required: true %>
</div>

<div class="form-group">
  <%= form.label :package %>
  <%= form.text_field :package,class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :remark %>
  <%= form.text_area :remark,class: "form-control", rows: "5" %>
</div>

<%= form.hidden_field :status,value: "Booked" %>

<%= form.submit :submit,class: "btn btn-default" %>

app/views/sales/_salevalue.html.erb
  <div class="col-xs-5 col-sm-5 col-md-5">
    <%= sv_form.select :user_id,options_for_select(User.all.order("prefered_name").pluck(:prefered_name,:id),:selected => sv_form.object.user_id),{:prompt => "Select"},{class: "form-control",required: true} %>
  </div>

  <div class="col-xs-5 col-sm-5 col-md-5">
   <%= sv_form.number_field :percentage, class: "form-control",min: "0",max: "100",step: "any",required: true%>
  </div>

  <div class="col-xs-1 col-sm-1 col-md-1">
  <%= sv_form.link_to_remove "-",class: "ren_remove btn btn-default" %>
  </div>

app/views/sales/_salevalue2.html.erb
  <div class="col-xs-5 col-sm-5 col-md-5">
    <%= sv2_form.fields_for :user, User.new do |ren_form| %>

		    <%= ren_form.text_field :prefered_name,placeholder: "Name",class: "form-control",required: true%>

		    <%= ren_form.hidden_field :password, :value => "eliteonesales2017"%>

    <%end%>
  </div>

  <div class="col-xs-5 col-sm-5 col-md-5">
   <%= sv2_form.number_field :percentage,placeholder: "Percentage (%)", class: "form-control",min: "0",max: "100",step: "any",required: true%>
  </div>

  <div class="col-xs-1 col-sm-1 col-md-1">
  <%= sv2_form.link_to_remove "-",class: "ren_remove btn btn-default" %>
  </div>

app/views/sales/_unit.html.erb
<div class="form-group">
  <%= unit_form.label :unit_no %>
  <%= unit_form.text_field :unit_no,class: "form-control" %>
</div>

<div class="form-group">
  <%= unit_form.label :unit_size %>
  <%= unit_form.number_field :size,class: "form-control",min: "0",step: "any" %>
</div>

<div class="form-group">
  <%= unit_form.label :spa_value %>
  <%= unit_form.number_field :spa_price,class: "form-control",min: "0",step: "any", required: true %>
</div>

<div class="form-group">
  <%= unit_form.label :nett_value %>
  <%= unit_form.number_field :nett_price,class: "form-control",min: "0",step: "any", required: true %>
</div>

app/views/sales/edit.html.erb
<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4 well">
<div class="col-lg-12">
<h1 class="page-header">Edit Sale #<%=@sale.id%></h1>
</div>

<%=nested_form_for @sale do |form|%>

<%=render "edit", form: form%>

<div class="col-xs-2 col-sm-2 col-md-2">
<%= form.submit "Update",class: "btn btn-default",style: "margin-left: -15px;" %>
</div>
<%end%>


<div style="float:right">
<button data-toggle="modal" data-target="#deleteModal" class="btn btn-default">Delete</button>
</div>
<div style="float:left">
<button data-toggle="modal" data-target="#emailModal" class="btn btn-default">Email Admin</button>
</div>
</div>

<div id="deleteModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-body">
        <h3>Delete Sale #<%=@sale.id%>?</h3>
      </div>
      <div class="modal-footer">
      	<%= link_to "/sales/#{@sale.id}",class: "btn btn-default",style: "float:left", method: :delete do%>Yes<%end%>
        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
      </div>
    </div>

  </div>
</div>

<%=render "emailModal"%>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sales</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4 well">
<div class="col-lg-12">
<h1 class="page-header">New Sale</h1>
<div>
<%=nested_form_for @sale do |form|%>

<%=render partial: "form", object: form%>
<%end%>
</div>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>